### ISSUE TITLE
Errer Showing

### ISSUE THREAD

**Issue by asifagaria** [pixelead0/tmdb_v3-PHP-API-#61]
Fatal error: Class 'ApiBaseObject' not found in C:\xampp\htdocs\tmdb\controller\classes\data\Movie.php on line 12

**Comment by bogdanfinn** [comment]
Seems like this has something to do with the namespacing and composer.json stuff ... 
Will look into it later and try to fix it.

**Comment by isarjanfaza** [comment]
hi
I also have a problem with what to do

**Comment by isarjanfaza** [comment]
Fatal error: Class 'ApiBaseObject' not found in /public_html/tmdb/controller/classes/data/Movie.php on line 12

**Comment by TimTim74** [comment]
I get the same problem. Even the examples give the same error:

Fatal error: Class 'ApiBaseObject' not found in /var/www/html/projects/tmdb-api/controller/classes/data/Movie.php on line 12

**Comment by ChrisTERiS** [comment]
Same fatal error (Class 'ApiBaseObject' not found) not only to Movie.php but to all.
And as it's already 8 full months since the first bug report, seems that nobody is interest to fix it.
If you've abandoned this (very promising) class, is more fair to remove it, respecting the time that someone waste for download, install, and testing it.

**Comment by bogdanfinn** [comment]
@asifagaria @isarjanfaza @TimTim74 @ChrisTERiS 
I pushed a temporary fix for the problem on my fork here:
https://github.com/bogdanfinn/tmdb_v3-PHP-API-

The examples are working if you check out this version and add your TMDB Api Key in the `configuration/default.php` file. Maybe you have to adjust the config, depending on the data you want to query. There is also a `configuration/all.php` file.

I think this library is not actively maintained. And to be honest i currently have not enough time to look deeper into the problem and get it fixed with the namespacing. introduced a few commits before.

**Comment by bogdanfinn** [comment]
and yeah the error has nothing to do with the class itself.
an important line was removed due to a merge conflict. this line imported the class. that was the actual error ;-)

**Comment by ChrisTERiS** [comment]
@bogdanfinn 
I'm still getting error when I applied your new code. But maybe I need to double check the files again.
Before your post, I've added at the top of require:
`require ("controller/classes/data/ApiBaseObject.php");`
but then I was getting error:
Fatal error: Cannot declare class ApiBaseObject, because the name is already in use

**Comment by ChrisTERiS** [comment]
Ok, now it works :) Have did so many changes in the code trying to fix it. The best that I had succeeded to get is the example page but without submenus :)
I was so in rush that I post a micro project to Freelancer . com :)

**Comment by ChrisTERiS** [comment]
@bogdanfinn Are you getting custom (paid) examples coding of this class?

**Comment by bogdanfinn** [comment]
@ChrisTERiS glad to read that it works now.
i used this library a long time ago as a base for a private project.

what examples do you need? maybe i could explain how to code it or add them to the repo if i find time.

**Comment by TimTim74** [comment]
My solution was to this this repo: https://github.com/femotizo/tmdb_v3-PHP-API-. Maybe not the latest, but it does what I need perfectly.

**Comment by bogdanfinn** [comment]
@ChrisTERiS 
Sorry for the late reply. My Github did not show me any answers to this issue.

> I need an example which will do:
> 1.- Fetcth data for a Movie or TV Show and save them in a MySQL database
> 2.- Copy Poster, Backdrop and images to my site
> 3.- Fetch data for crew (actors) only and save them in database (checking for duplicates).

1) For this we already have examples in this repo i think. Except of the MySQL database part. Personally i would not want to implement examples for the persistence layer because this is a dependency and has nothing to do with this repository (in my opinion). This repository is just about receiving data not storing them in some database. Also it would highly depend on the question if you use plain SQL Statements or an ORM and so on ...
2) Dont know why you need to copy the images and tbh i'm not sure if you actually are allowed to copy the images. But you can just store the URL to the images?
3) Same as Answer to 1 i think. There are already examples for "Persons". On a Person you are able to receive the Roles (Movie or TVShow Roles). Nevertheless coming from a Movie or a TVShow you are able to call `getCast()` on it to receive a List of Person Objects.

**Comment by ChrisTERiS** [comment]
Hello Captain 😊

Can I ask you something if you don’t mind? Is it possible to add a function to TVShow.php to get the cast ids for a TVShow and then add a foreach loop to tvshowsExample.php to display the id + name of the actor?

I don’t want to confuse things more by asking for crew. Just Cast is fine for me.

Don’t know how heavy work is what I’m asking for, but if you want it as paid job, please tell me how much money you want. Sure, you’ll be able to include it in the public release, no problem from my side.

Thank you,
Chris


Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για Windows 10

Από: CaptainBarnius<mailto:notifications@github.com>
Αποστολή: Κυριακή, 5 Ιουλίου 2020 0:04
Προς: pixelead0/tmdb_v3-PHP-API-<mailto:tmdb_v3-PHP-API-@noreply.github.com>
Κοιν.: ChrisTERiS<mailto:christos.teriakis@outlook.com>; Mention<mailto:mention@noreply.github.com>
Θέμα: Re: [pixelead0/tmdb_v3-PHP-API-] Errer Showing (#61)


@ChrisTERiS<https://github.com/ChrisTERiS>
Sorry for the late reply. My Github did not show me any answers to this issue.

I need an example which will do:
1.- Fetcth data for a Movie or TV Show and save them in a MySQL database
2.- Copy Poster, Backdrop and images to my site
3.- Fetch data for crew (actors) only and save them in database (checking for duplicates).

  1.  For this we already have examples in this repo i think. Except of the MySQL database part. Personally i would not want to implement examples for the persistence layer because this is a dependency and has nothing to do with this repository (in my opinion). This repository is just about receiving data not storing them in some database. Also it would highly depend on the question if you use plain SQL Statements or an ORM and so on ...
  2.  Dont know why you need to copy the images and tbh i'm not sure if you actually are allowed to copy the images. But you can just store the URL to the images?
  3.  Same as Answer to 1 i think. There are already examples for "Persons". On a Person you are able to receive the Roles (Movie or TVShow Roles). Nevertheless coming from a Movie or a TVShow you are able to call getCast() on it to receive a List of Person Objects.

**Comment by bogdanfinn** [comment]
@ChrisTERiS 
Please Check `/examples/movies/infoMovie.php` and `/examples/tvshows/infoTVShow.php` i already created examples for Cast & Crew on both, Movies and TVShows. 

@pixelead0 we should close this issue, because it is actually done.
